export const DEFAULT_CURRENT_TEMPERATURE_F = 70;
export const DEFAULT_HEAT_SETPOINT_F = 68;
export const DEFAULT_COOL_SETPOINT_F = 76;
export const LOW_BATTERY_THRESHOLD = 20;
export const DEFAULT_WRITE_BARRIER_MS = 5_000;
export const LOCK_WRITE_BARRIER_MS = 15_000;
